version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env/development/database
      - .env/development/web
    volumes:
    - .:/usr/src/app
    tty: true
    stdin_open: true

  database:
    image: postgres
    env_file:
      - .env/development/database
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env/development/pgadmin
    ports:
    - "8080:80"
    links:
      - "database:pgsql"

